# Generated by Django 4.0.4 on 2022-04-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maids_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
