# Generated by Django 4.0.4 on 2022-04-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maids_api', '0002_alter_newuser_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
    ]
