# Generated by Django 4.0.4 on 2022-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maids_api', '0003_rename_owner_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
