# Generated by Django 4.0.4 on 2022-04-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maids_api', '0007_alter_comment_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
