# Generated by Django 4.0.4 on 2022-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maids_api', '0008_remove_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
