# Generated by Django 4.0.4 on 2022-04-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maids_api', '0009_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(max_length=10),
        ),
    ]
